services:
    controller.api.event_groups_list:
        class: AppBundle\Controller\Api\EventGroupsListController
        autowire: true

    controller.api.create_event:
        class: AppBundle\Controller\Api\CreateEventController
        autowire: true

    controller.api.events_list:
        class: AppBundle\Controller\Api\EventsListController
        autowire: true

    controller.api.reservations_list:
        class: AppBundle\Controller\Api\ReservationsListController
        autowire: true
