services:
    controller.api.register:
        class: AppBundle\Controller\Api\RegisterController
        autowire: true

    controller.admin_api.event_groups_list:
        class: AppBundle\Controller\AdminApi\EventGroupsListController
        autowire: true

    controller.admin_api.create_event:
        class: AppBundle\Controller\AdminApi\CreateEventController
        autowire: true

    controller.admin_api.events_list:
        class: AppBundle\Controller\AdminApi\EventsListController
        autowire: true

    controller.admin_api.reservations_list:
        class: AppBundle\Controller\AdminApi\ReservationsListController
        autowire: true
