services:
    model.event_group:
        class: AppBundle\Model\EventGroup\EventGroupModel
        arguments:
          - '@repository.event_group'

    model.event.create:
        class: AppBundle\Model\Event\CreateEventModel
        arguments:
          - '@repository.event'

    model.events.list:
        class: AppBundle\Model\Event\EventsListModel
        arguments:
          - '@repository.event'

    model.reservations.list:
        class: AppBundle\Model\Reservations\ReservationsListModel
        arguments:
          - '@repository.reservation'

    model.reservations.create:
        class: AppBundle\Model\Reservations\CreateReservationModel
        arguments:
          - '@repository.reservation'
          - '@repository.event'
          - '@validator'
          - '@reservation_email'