app:
    resource: "@AppBundle/Controller/Admin"
    type:     annotation
    prefix:   /api/admin

api:
    resource: "@AppBundle/Controller/Api"
    type:     annotation
    prefix:   /api

logout:
    path: /logout