admin:
    resource: "@AppBundle/Controller/Admin"
    type:     annotation
    prefix:   /admin

admin_api:
    resource: "@AppBundle/Controller/AdminApi"
    type:     annotation
    prefix:   /adminApi

api:
    resource: "@AppBundle/Controller/Api"
    type:     annotation
    prefix:   /
