imports:
    - { resource: services/repositories.yml }
    - { resource: services/models.yml }
    - { resource: services/controllers.yml }

services:
    response_creator:
        class: AppBundle\Services\Response\ResponseCreator
        autowire: true

    reservations_to_csv:
        class: AppBundle\Services\Csv\ExportReservationsToCsv
        autowire: true

    reservation_email:
        class: AppBundle\Services\Email\ReservationEmail
        autowire: true