imports:
    - { resource: services/repositories.yml }
    - { resource: services/models.yml }
    - { resource: services/controllers.yml }

services:
    response_creator:
        class: AppBundle\Services\Response\ResponseCreator
        arguments:
          - '@serializer'